#开发人员配置
spring:
    datasource:
        name: adminDev
        url: jdbc:log4jdbc:mysql://127.0.0.1/carp?useUnicode=true&characterEncoding=utf-8&useSSL=false
        # 使用druid数据源
        driver-class-name: net.sf.log4jdbc.DriverSpy
        #dev 不用wall设置
        filters: stat,log4j
    freemarker:
        cache: false

    #jpa自动生成sql
    jpa:
      show-sql: false
      properties:
        javax:
         persistence:
           schema-generation:
            create-source:  metadata
            scripts:
              action: create
              create-target: carp_reate.sql
#flyway配置
flyway:
  enabled: true